Add files via upload

diff --git a/daemon/daemon b/daemon/daemon
--- a/daemon/daemon
+++ b/daemon/daemon
@@ -16,26 +16,40 @@ cmd="ps ux | grep syno_plugin.py | grep -v grep"
 start="python $LBPBIN/$PLUGINDIR/syno_plugin.py"
 stop="kill $(ps aux | grep "[p]ython $LBPBIN/$PLUGINDIR/syno_plugin.py" | awk '{print $2}')"
 
+function get_pid() {
+	# get process ID 
+	PID=$(ps aux | grep "[p]ython $LBPBIN/$PLUGINDIR/syno_plugin.py" | awk '{print $2}')
+	if [ $PID ]; then
+		# write the process ID into a lock file
+		echo $PID > /tmp/syno_plugin.lock
+		/usr/bin/logger "<INFO> syno_plugin was started. Process ID: $PID"
+		exit 0
+	else
+		# if there is no process ID, plugin is not running -> remove the lock file
+		if [ -a /tmp/syno_plugin.lock ]; then rm /tmp/syno_plugin.lock; fi
+		/usr/bin/logger "<ERROR> syno_plugin was NOT started..."
+		exit 1
+	fi
+}	
+
 # run the command to check
 eval "$cmd" > /dev/null 2>&1
 
 # did the previous command return a non-zero exit code?
 if [ $? -ne 0 ]; then
-    is_running=0    # syno_plugin is stopped
+	is_running=0    # syno_plugin is stopped
 else
-    is_running=1    # syno_plugin is running
+	is_running=1    # syno_plugin is running
 fi
 
 case "$1" in
     start)
         if [ $is_running = 0 ]; then
             $start &
-            touch /tmp/syno_plugin.lock
-            /usr/bin/logger "<INFO> syno_plugin was started..."
-            exit 0
+			get_pid
         else
             /usr/bin/logger "<INFO> syno_plugin is already running"
-            exit 0
+            exit 1
         fi
     ;;
     stop)
@@ -46,7 +60,7 @@ case "$1" in
             exit 0
         else
             /usr/bin/logger "<INFO> syno_plugin is not running"
-            exit 0
+            exit 1
         fi
     ;;
     restart)
@@ -56,14 +70,10 @@ case "$1" in
             /usr/bin/logger "<INFO> syno_plugin was stopped..."
             #sleep 3
             $start &
-            touch /tmp/syno_plugin.lock
-            /usr/bin/logger "<INFO> syno_plugin was started..."
-            exit 0
+            get_pid
         else
             $start &
-            touch /tmp/syno_plugin.lock
-            /usr/bin/logger "<INFO> syno_plugin was started..."
-            exit 0
+            get_pid
         fi
     ;;
     status)
@@ -80,8 +90,5 @@ case "$1" in
     exit 0
     ;;
 esac
-
-$LOG "<INFO> Current LoxBerry version is $BASEVERSION\n"
-$LOG "<INFO> You have a count of $BASEMINISERVERS configured\n"
 
 exit 0
